version: '2'
services:
  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    command: [nginx-debug, '-g', 'daemon off;']
    links:
      - movies
      - bookings
      - showtimes
      - users
    ports:
      - "8080:80"

  kong-migration:
    build: ./kong
    # volumes:
    #   - ../kong-notification-plugin/kong/plugins/notification:/usr/local/share/lua/5.1/kong/plugins/notification:ro
    links:
      - kong-postgres
    restart: on-failure
    environment:
      - KONG_DATABASE=postgres
      - KONG_PG_HOST=kong-postgres
      - KONG_PG_PASSWORD=password
      # - KONG_CUSTOM_PLUGINS=notification
    command: kong migrations up

  # kong-migration-test:
  #   build: ./kong
  #   volumes:
  #     - ../kong-notification-plugin/kong/plugins/notification:/usr/local/share/lua/5.1/kong/plugins/notification:ro
  #   links:
  #     - kong-postgres-test
  #   environment:
  #     - KONG_DATABASE=postgres
  #     - KONG_PG_HOST=kong-postgres-test
  #     - KONG_PG_DATABASE=kong_tests
  #     - KONG_CUSTOM_PLUGINS=notification
  #   command: kong migrations up

  kong:
    build: ./kong
    # volumes:
    #   - ../kong-notification-plugin/kong/plugins/notification:/usr/local/share/lua/5.1/kong/plugins/notification:ro
    #   - ../kong-notification-plugin/spec/handler_spec.lua:/home/kong/spec/handler_spec.lua:ro
    #   - ../kong-notification-plugin/spec/01-access_spec.lua:/home/kong/spec/01-access_spec.lua:ro
    environment:
      - KONG_DATABASE=postgres
      - KONG_PG_HOST=kong-postgres
      - KONG_PG_PASSWORD=password
      - KONG_LOG_LEVEL=debug
      - KONG_PROXY_ACCESS_LOG=/dev/stdout
      - KONG_ADMIN_ACCESS_LOG=/dev/stdout
      - KONG_PROXY_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_LISTEN=0.0.0.0:8001
      # - KONG_CUSTOM_PLUGINS=notification
    restart: on-failure
    links:
      - movies
      - bookings
      - showtimes
      - users
      - kong-postgres
      # - kong-postgres-test
    depends_on:
      - kong-migration
      # - kong-migration-test
    ports:
      - "9000:8000"
      - "9001:8001"

  kong-postgres:
    image: postgres:alpine
    environment:
      - POSTGRES_DB=kong
      - POSTGRES_USER=kong
      - POSTGRES_PASSWORD=password
    ports:
      - "5433:5432"

  # kong-postgres-test:
  #   image: postgres:alpine
  #   environment:
  #     - POSTGRES_DB=kong_tests
  #     - POSTGRES_USER=kong
  #   ports:
  #     - "5434:5432"

  movies:
    build: ./movies

  bookings:
    build: ./bookings

  showtimes:
    build: ./showtimes

  users:
    build: ./users
    links:
      - bookings
      - movies
